flask/website/views/documentation.py
from flask import (
	Blueprint,
	render_template,
	request,
	redirect,
	url_for,
	escape
)
from flask_login import login_required, current_user
from flask_mobility.decorators import mobile_template
from ..models import ORM

mod = Blueprint('documentation', __name__)


@mod.route('/faq/', methods=['GET'])
@mobile_template('{mobile/User/}faq.html')
@login_required
def faq(template):
	data = ORM.get_faq_json()
	topic = set()
	for reponse in data.values():
		topic.add(reponse["topic"])
	return render_template(
		template,
		data=data,
		topic=list(topic),
		devices = ORM.get_devices_by_username(current_user.username_user)
	)

@mod.route("/guide/",methods=['GET'])
@mobile_template('{mobile/User/}guide.html')
def guide(template):
	return render_template(template)

flask/website/views/index.py
from flask import (
    Blueprint,
    render_template,
    request,
    redirect,
    url_for,
    escape,
)
from flask_mobility.decorators import mobile_template
from flask_login import current_user, logout_user

mod = Blueprint('index', __name__)

@mod.route('/', methods=['GET', 'POST'])
@mobile_template('{mobile/Authentification/}index.html')
def index(template):
    if current_user.is_authenticated:
        logout_user()
    return render_template(template)

flask/website/views/login.py
from flask import (
    Blueprint,
    render_template,
    redirect,
    request,
    url_for,
    current_app
)
from flask_mobility.decorators import mobile_template

from wtforms import (
    StringField,
    PasswordField,
    HiddenField
)
from wtforms.validators import DataRequired
from flask_wtf import FlaskForm
from flask_mobility.decorators import mobile_template
from flask_login import login_required, login_user, logout_user, current_user
from ..models import ORM
from hashlib import sha256
from flask.helpers import flash

mod = Blueprint('login', __name__)


class LoginForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    next = HiddenField()

    def get_data(self):
        return self.username.data

    def get_authenticated_user(self):
        user = ORM.load_user(self.username.data)
        if user is None:
            return None
        m = sha256()
        m.update(self.password.data.encode())
        passwd = m.hexdigest()
        return user if passwd == user.password_user else None


@mod.route('/login/', methods=['GET', 'POST'])
@mobile_template("{mobile/Authentification/}login.html")
def login(template):
    if current_user.is_authenticated:
        logout_user()
    f = LoginForm()
    if not f.is_submitted():
        f.next.data = request.args.get("next")
    elif f.validate_on_submit():
        user = f.get_authenticated_user()
        if user:
            if not ORM.is_blocked_account_user(user.username_user):
                login_user(user)
                if user.is_admin_user:
                    next = f.next.data or url_for("admin.admin_home")
                else:
                    next = f.next.data or url_for("home.home")
                return redirect(next)
            else:
                flash("Your account has been blocked. Please contact us if it is an error.","error")
                return redirect(url_for("login.login"))
        else:
            flash("Incorrect logins.","error")
    return render_template(
        template,
        form=f,
    )

flask/website/views/register.py
from flask import render_template, request, redirect, url_for, escape
from flask import Blueprint
from hashlib import sha256
from ..models import ORM
from flask_mobility.decorators import mobile_template
from ..app import db, mail, app
from ..models import USER, DEVICE
from flask.helpers import flash
import datetime
from ..utils import Utils
from flask_mail import Message
import os
from flask_login import current_user, logout_user
mod = Blueprint('register', __name__)


@mod.route('/register/', methods=['GET', 'POST'])
@mobile_template('{mobile/Authentification/}register.html')
def register(template):
	if current_user.is_authenticated:
		logout_user()
	subscriptions = ORM.get_subscriptions()
	features = Utils.str_collon_to_list(ORM.get_subscriptions_features()[0])
	return render_template(
		template,
		subscriptions=subscriptions,
		features=features
	)


def send_welcome_email(username, email):
	"""
	Send the welcome message to the new user.
	"""
	page = "<html>" \
	       "<body>" \
	       "<h1>Welcome ! 🔥</h1>" \
	       "<h2>Hello<b> " + username + "</b>, Welcome in Bikeeper! Your account is now registered on " \
	                                   "our web site. Your can log in into your account to start using " \
	                                   "your device.</h2><br><img src=cid:logo></body></html> "
	msg = Message(subject="Welcome from Bikeeper ! ", html=page, sender='bikeeper34@gmail.com',
	              recipients=[email])
	with open('website/static/pc/assets/logo_bikeeper.png', 'rb') as fp:
		msg.attach('logo_bikeeper.png', 'image/png', fp.read(), 'inline', headers=[['Content-ID', '<logo>']])
	mail.send(msg)


@mod.route('/register/validate/', methods=['GET', 'POST'])
def register_validate():
	username = str(escape(request.form['username']))
	email = str(escape(request.form['email']))
	password = str(escape(request.form['password']))
	confirmpassword = str(escape(request.form['confirmpassword']))
	phonenumber = str(escape(request.form['tel']))
	address = str(escape(request.form['address']))
	city = str(escape(request.form['city']))
	postalcode = str(escape(request.form['postalcode']))
	selected_device = ORM.get_new_num_device()
	is_account_blocked = False
	date_creation_user = datetime.datetime.now()
	name_subscription = str(escape(request.form['sub']))

	informations = {
		"username": username,
		"email": email,
		"password": password,
		"confirmpassword": confirmpassword,
		"phonenumber": phonenumber,
		"address": address,
		"city": city,
		"postalcode": postalcode,
	}

	valid, message = ORM.is_valid_register(informations)

	if valid:
		m = sha256()
		m.update(password.encode())
		u = USER(
			username, m.hexdigest(), phonenumber, "", "", email, city, postalcode, address,
			f"https://eu.ui-avatars.com/api/{username}", False, selected_device, is_account_blocked,
			date_creation_user, name_subscription)
		db.session.add(u)

		d = DEVICE(selected_device, Utils.read_prefixes(), None, username)
		db.session.add(d)

		db.session.commit()

		send_welcome_email(username, email)

		flash(message, "success")
		return redirect(url_for('login.login'))
	else:
		flash(message, "error")
		return redirect(url_for('register.register'))

flask/website/templates/mobile/Authentification/index.html
{% extends "mobile/base.html" %}

{% block title %}
{{ super() }}
{% endblock %}

{% block style %}
<link rel="stylesheet" href="{{ url_for('static', filename='mobile/css/Authentification/index-mobile.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='mobile/css/Authentification/overlay.css') }}">
{% endblock %}

{% block header %}
        <div class="logo">
            <a href="{{ url_for('index.index') }}"><img src="{{ url_for('static', filename='mobile/assets/logo_bikeeper_without_text.png') }}" alt="logo BiKeeper">
            <h1>BiKeeper</h1></a>
        </div>

        {% include "components/mobile-sidebar-guest.html" %}
        <!-- Use any element to open/show the overlay navigation menu -->
        <nav onclick="openNav()"><img src="{{ url_for('static', filename='mobile/assets/menu.png') }}" alt="logo menu"></nav>
{% endblock %}

{% block main %}

        <div class="header"></div>
        <div class="background-avec-image"></div>
        <div class = bien-tout-placer>
            <h2><span style="color: #FFFFFF; ">Protect your bike</span><span style="color: #DC1D21; ">.</span></h2>
            <div class="avis">
                <div class="mini-header">
                    <img src="{{ url_for('static', filename='mobile/assets/magazine.png') }}" alt="magazine" id="magazine">
                    <h4>Motorbike Magazine</h4>
                    <img src="{{ url_for('static', filename='mobile/assets/thumb-up.png') }}" alt="magazine" id="thumb-up">
                </div>
                <div class ="rate">
                    <span>&starf;&starf;&starf;&starf;&starf;</span>
                    <p>3 days ago</p>
                </div>
                <p>
                    The <strong>best</strong> tracker for <strong>your motorbike</strong>. Simple to use, a lot of features, for a small price ! <strong>BiKeeper</strong> will <strong>protect</strong> your <strong>motorbike</strong> from theft. 
                        Localisation, statistics, fail detector... <strong><span
                        style="color: #0CA6F2; ">read more</span></strong>
                </p>
            </div>
        </div>
        <article>
            <h3>What is BiKeeper<span style="color: #DC1D21; ">?</span></h3>
            <p>
                <strong>BiKeeper</strong> is a GPS tracker. BiKeeper is <strong>connected</strong> everywhere and <strong>linked to our powerfull software</strong>. When we <strong>detect theft</strong>, a <strong>notification</strong> is <strong>automaticaly sent</strong> to the motorbike <strong>owner</strong>.
            </p>
        </article>
        <div class="localisation">
            <div>
                <h5>Localisation in real time</h5>
                <p>See where is your vehicle on a map directly in a web browser...</p>
                <a href="{{ url_for('login.login') }}">Login on our website to track.</a>
            </div>
            <img src="{{ url_for('static', filename='mobile/assets/localisation-1.png') }}" alt="loupe.png">
        </div>
        <article>
            <h3>How does it work<span style="color: #DC1D21; ">?</span></h3>
            <p><!-- TODO CHANGE -->
                Within your vehicle lies the <strong>Bikeeper</strong> device, his function is to read many kinds of data and then send them to you in your account. <strong>Bikeeper</strong> wants you to feel <strong>protected</strong> and <strong>assured</strong> therefore you can access to all of the <strong>details</strong> the device received (the state of your vehicle, and your last rides) and it will send <strong>notifications</strong> if something happens either to you or your vehicle. Furthermore, if you are connected and you have an accident, your device will automatically send a <strong>message</strong> to one of your contact. What are you waiting to join our community? Ride safe! <a id="guide" href="{{ url_for('documentation.guide') }}"> Read More</a></p>
        </article>

{% endblock %}

flask/website/templates/mobile/Authentification/login.html
{% extends "mobile/base.html" %}

{% block title %}
{{ super() }} | Login
{% endblock %}

{% block style %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='mobile/css/Authentification/login-mobile.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='mobile/css/Authentification/header-mobile.css') }}"> 
    <link rel="stylesheet" href="{{ url_for('static', filename='mobile/css/Authentification/overlay.css') }}">
{% endblock %}

{% block header %}

    <div class="logo">
        <a href="{{ url_for('index.index') }}">
            <img src="{{ url_for('static', filename='mobile/assets/logo_bikeeper_without_text.png') }}" alt="logo BiKeeper">
            <h1>BiKeeper</h1>
        </a>
    </div>
    {% include "components/mobile-sidebar-guest.html" %}
    <!-- Use any element to open/show the overlay navigation menu -->
    <nav onclick="openNav()"><img src="{{ url_for('static', filename='mobile/assets/menu.png') }}" alt="logo menu"></nav>
{% endblock %}

{% block main %}
<main class='login-main'>
    <div class="flash">
        {% include "messages.html" %}
    </div>
    <h2>
        Login to access your account
    </h2>
    <form action="#" method="POST">
        {{ form.hidden_tag() }}
        <div>

            <label for="username">Username</label>
            {{ form.username(size=50, id="username", placeholder="Enter your username") }}
        </div>
        <div>
            <label for="password">Password</label>
            {{ form.password(size=50, id="password", placeholder="Enter your password") }}
        </div>

        <button type="submit" class="login"><span>Login</span></button>
    </form>
    <div id="rectangle"></div>
</main>
{% endblock %}

{% block script %}
{% endblock %}

flask/website/templates/mobile/Authentification/register.html
{% extends "mobile/base.html" %}

{% block title %}
{{ super() }} | Register
{% endblock %}

{% block style %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
<link rel="stylesheet" href="{{ url_for('static', filename='mobile/css/Authentification/header-mobile.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='mobile/css/Authentification/overlay.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='mobile/css/Authentification/register-mobile.css') }}">
{% endblock %}

{% block header %}
        <div class="logo">
            <a href="{{ url_for('index.index') }}">
                <img src="{{ url_for('static', filename='mobile/assets/logo_bikeeper_without_text.png') }}" alt="logo BiKeeper">
                <h1>BiKeeper</h1>
            </a>
        </div>
        {% include "components/mobile-sidebar-guest.html" %}
        <!-- Use any element to open/show the overlay navigation menu -->
        <nav onclick="openNav()"><img src="{{ url_for('static', filename='mobile/assets/menu.png') }}" alt="logo menu"></nav>
{% endblock %}   

{% block main %}
        <form action="{{url_for('register.register_validate')}}" method="POST">
            <div class="flash">
                {% include "messages.html" %}
            </div>
            <div class="information">
                <h2>Create your account</h2>
                <div>
                    <label for="username">Username</label>
                    <input type="text" id='username' name="username" placeholder='Enter your username' required>
                </div>
                <div>
                    <label for="email">Email</label>
                    <input type="text" id='email' name="email" placeholder='Enter your email' required>
                </div>
                <div>
                    <label for="password">Password</label>
                    <input type="password" id='password' name="password" placeholder='Enter your password' required>
                </div>
                <div>
                    <label for="confirmpassword">Confirm your password</label>
                    <input type="password" id='confirmpassword' name="confirmpassword" placeholder='Confirm your password' required>
                </div>
            </div>


            <div class="information">
                <h2>Where should we send your device ?</h2>
                <div>
                    <label for="tel">Phone Number</label>
                    <input type="tel" id='tel' name="tel" placeholder='06.12.54.63.95' required>
                </div>
                <div>
                    <label for="address">Address</label>
                    <input type="text" id='address' name="address" placeholder='3170 Broadway #8G' required>
                </div>
                <div>
                    <label for="city">City</label>
                    <input type="text" id='city' name="city" placeholder='New York' required>
                </div>
                <div>
                    <label for="postalCode">Postal Code</label>
                    <input type="text" id='postalCode' name="postalcode" placeholder='10029' required>
                </div>
            </div>

            <div class="register-subscription">
                <h2>Subscriptions</h2>
                {% for sub in subscriptions %}
                    {% if sub.name_subscription == "France" %}
                    <section class='section-sub'>
                    {% else %}
                    <section class='section-sub selected-sub'>
                    {% endif %}
                        <h2>{{sub.name_subscription}}</h2>
                        <div>
                        <h4>{{sub.localisation_subscription}}</h4>
                            <ul>
                                {% for feature in  features %}
                                    {% if sub.name_subscription == "France" and feature == "World Wide Localisation"%}
                                        <s>{{feature}}</s>
                                    {% else %}
                                        <li>{{feature}}</li>
                                    {% endif %}
                                {% endfor %}
                            </ul> 
                        </div>
                        
                        <div class="sub-radio">
                            <div><span onclick="selectSub(this)">Choose this plan - €{{sub.price_subscription}}/mo</span></div>
                            <input type="radio" name="sub" value="{{sub.name_subscription}}" checked>
                        </div>
                    </section>
                {% endfor %}
            </div>


            <div id="credit-card">
                <h3>Credit Card</h3>
                <img src="{{ url_for('static', filename='mobile/assets/mastercard.png') }}" alt="master card logo">
                <fieldset>
                    <legend>Card number</legend>
                    <input type="text" id='username' name="username" placeholder='1234 - 5678 - 9123 - 4567'>
                </fieldset>
                <fieldset>
                    <legend>Card Holder Name</legend>
                    <input type="text" id='username' name="username" placeholder='John Doe'>
                </fieldset>
                <fieldset>
                    <legend>Expiration Date</legend>
                    <input type="text" id='username' name="username" placeholder='08/22'>
                </fieldset>
                <fieldset>
                    <legend>CVV/CVC</legend>
                    <input type="text" id='username' name="username" placeholder='666'>
                </fieldset>   
            </div>                                 
            <button type="submit" class="register"><span>Register</span></button>
        </form>
        <div id="rectangle"></div>
{% endblock %}   

{% block script %}
<script src="{{ url_for('static', filename='pc/js/subscription.js') }}"></script>
{% endblock %}