flask/website/views/admin.py
from flask import (
	Blueprint,
	render_template,
	session,
	redirect,
	abort,
	url_for,
	request
)
from flask_mobility.decorators import mobile_template
from flask_login import login_required, login_user, logout_user, current_user
from functools import wraps
from ..models import ORM

mod = Blueprint('admin', __name__)


def admin_required(f):
	@wraps(f)
	def wrap(*args, **kwargs):
		if not current_user.is_admin_user:
			abort(403, description="Can't access an admin page as user")
		return f(*args, **kwargs)

	return wrap


@mod.route('/admin/access', methods=['GET'])
@mobile_template("{mobile/Admin/}admin_access.html")
@login_required
@admin_required
def admin_access(template):
	return render_template(template)


@mod.route('/admin/home', methods=['GET'])
@mobile_template("{mobile/Admin/}admin_home.html")
@login_required
@admin_required
def admin_home(template):
	return render_template(
		template,
		nb_users=ORM.get_number_of_user(),
		tt_data=ORM.get_space_used_database(),
		nb_ticket=ORM.get_number_open_ticket(),
		nb_bikeeper=ORM.get_number_of_bikeeper(),
		nb_ride=ORM.get_total_number_rides(),
		nb_alert=ORM.get_total_number_alerts()
	)


@mod.route('/admin/support', methods=['GET'])
@mobile_template("{mobile/Admin/}admin_support.html")
@login_required
@admin_required
def admin_support(template):
	return render_template(template)


@mod.route('/admin/platform', methods=["GET"])
@login_required
@admin_required
def platform():
	return render_template('admin_platform.html')

flask/website/views/home.py
from flask import (
	Blueprint,
	render_template,
	session,
	redirect,
	request,
	url_for,
	abort
)
from flask_mobility.decorators import mobile_template
from flask_login import login_required, current_user
from ..models import ORM
from ..utils import Utils
from functools import wraps

mod = Blueprint('home', __name__)

PROD_MODE = True


def admin_forbidden(f):
	@wraps(f)
	def wrap(*args, **kwargs):
		if current_user.is_admin_user:
			abort(403, description="Admin forbidden")
		return f(*args, **kwargs)

	return wrap


@mod.route('/home/', methods=['GET', 'POST'])
@mobile_template('{mobile/User/}home.html')
@login_required
@admin_forbidden
def home(template):
	if PROD_MODE:  # In production the request ip is the ngnix ip. We forward ip in headers to keep real ip.
		ip_address = request.headers['X-Real-IP']
	else:
		ip_address = request.remote_addr
	ORM.log_ip(ip_address)
	devices = ORM.get_devices_by_username(current_user.username_user)
	selected_device = current_user.selected_device
	return render_template(
		template,
		devices=devices,
		selected_device=selected_device
	)


@mod.route('/localisation/', methods=['GET', 'POST'])
@login_required
@admin_forbidden
def localisation():
	return render_template(
		"mobile/User/localisation.html"
	)

flask/website/views/index.py
from flask import (
    Blueprint,
    render_template,
    request,
    redirect,
    url_for,
    escape,
)
from flask_mobility.decorators import mobile_template
from flask_login import current_user, logout_user

mod = Blueprint('index', __name__)

@mod.route('/', methods=['GET', 'POST'])
@mobile_template('{mobile/Authentification/}index.html')
def index(template):
    if current_user.is_authenticated:
        logout_user()
    return render_template(template)

flask/website/views/stats.py
import json

from flask import (
	Blueprint,
	render_template,
	session,
	redirect,
	url_for,
	request,
	current_app,
	abort
)
from flask_login import current_user, login_required

from ..models import ORM
from flask_mobility.decorators import mobile_template
from flask.helpers import flash
from functools import wraps

mod = Blueprint("stats", __name__)

def admin_required(f):
	@wraps(f)
	def wrap(*args, **kwargs):
		if not current_user.is_admin_user:
			abort(403, description="Can't access an admin page as user")
		return f(*args, **kwargs)

	return wrap

@mod.route('/statistics/', methods=['GET', 'POST'])
@mobile_template('{mobile/User/}stats.html')
@login_required
def statistics(template):
	search_user = request.form.get('search_user', default=None, type=str)

	if search_user is not None:  # ADMIN
		res = ORM.search_user(search_user)
		if len(res)!=0:
			res = res [0]
			devices = ORM.get_devices_by_username(res.username_user)
			price = ORM.get_price_from_subscription_name(res.name_subscription)
			is_blocked = ORM.is_blocked_account_user(res.username_user)
					
		else:
			flash("User not found.","error")
			return redirect(url_for('stats.statistics'))

		return render_template(
			template,
			username=res.username_user,
			phone=res.num_user,
			street=res.street_user,
			town=res.town_user,
			devices=devices,
			picture=res.profile_picture_user,
			date=res.date_creation_user,
			subscription=res.name_subscription,
			price=price,
			is_blocked=is_blocked
		)

	else:
		return render_template(
			template,
			username='',
			devices=ORM.get_devices_by_username(current_user.username_user),
			id_device =current_user.selected_device
		)

@mod.route('/statistics/unblock', methods=['GET', 'POST'])
@admin_required
@login_required
def statistics_unblock():
	username = request.form.get("username")
	if ORM.get_number_of_devices_by_username(username) > 0:
		ORM.unblock_user(username)
	else:
		flash("This user has left our community. He cannot be unblocked.","error")
	return redirect(url_for('stats.statistics'))

@mod.route('/statistics/block', methods=['GET', 'POST'])
@admin_required
@login_required
def statistics_block():
	username = request.form.get("username")
	ORM.block_user(username)
	return redirect(url_for('stats.statistics'))

@mod.route("/statistics/device/add", methods=['POST'])
@admin_required
@login_required
def add_device():
	num_device = request.form.get("number_device")
	username = request.form.get("user")
	ORM.new_user_device(username, num_device)
	return redirect(url_for('stats.statistics'))

flask/website/views/support.py
from flask import (
    Blueprint,
    render_template,
    session,
    jsonify,
    redirect,
    url_for,
    request,
    Response
)
from ..app import db
from ..models import ORM, TICKET, USER, MESSAGE
from flask_mobility.decorators import mobile_template
from flask_login import login_required, current_user

mod = Blueprint('support', __name__)


@mod.route('/support/', methods=['GET'])
@mobile_template('{mobile/User/}support.html')
@login_required
def support(template):

    messages = {}

    if not current_user.is_admin_user:
        open_tickets_user = ORM.get_open_ticket_user(current_user.username_user)

        if len(open_tickets_user) != 0:
            for ticket in open_tickets_user:
                messages[ticket.id_ticket] = [ORM.get_message_by_ticket_id(ticket.id_ticket),ticket.title_ticket]

    else:
        open_tickets = ORM.get_open_ticket()
        for ticket in open_tickets:
            messages[ticket.id_ticket] = [ORM.get_message_by_ticket_id(ticket.id_ticket),ticket.title_ticket]
    
    last_messages = {}
    for i_mes in messages.keys():
        last_messages[i_mes] = ORM.get_last_message_by_ticket_id(i_mes)

	# Avoid IndexError if there is no opened tickets

    try:
        first_ticket_id = list(messages.keys())[0]
    except IndexError:
        first_ticket_id = None

    return render_template(
        template,
        messages=messages,
        first_ticket_id=first_ticket_id,
        picture=ORM.get_picture_message_from_username(current_user.username_user),
        last_messages=last_messages,
        devices=ORM.get_devices_by_username(current_user.username_user)
    )


@mod.route('/support/<int:id_ticket>/', methods=['GET'])
@login_required
def support_message(id_ticket):
    return render_template(
        'mobile/User/support-bis.html',
        id_ticket=id_ticket,
        messages=ORM.get_message_by_ticket_id(id_ticket),
        picture=ORM.get_picture_message_from_username(current_user.username_user),
    )


@mod.route('/support/message/new', methods=['POST'])
@login_required
def support_message_new():
    if request.method == 'POST':
        contenu_message = request.json['content']
        is_admin = request.json['is_admin']
        date = request.json['date']
        id_ticket = request.json['id_ticket']
        username = request.json['username']

        msg = MESSAGE(is_admin, date, contenu_message, id_ticket, username)
        db.session.add(msg)
        db.session.commit()

        return Response(status=200)


@mod.route('/support/ticket/new', methods=['POST'])
@login_required
def support_new_ticket():
    title = request.form.get('ticket')
    if not current_user.is_authenticated:
        return redirect(url_for('login'))
    user = current_user.username_user
    ticket = TICKET(title, 0, user)
    db.session.add(ticket)
    db.session.commit()
    return redirect(url_for('support.support'))


@mod.route('/support/ticket/close/<string:id_ticket>', methods=['DELETE'])
@login_required
def support_delete_ticket(id_ticket):
    ORM.remove_tickets_by_id(id_ticket)
    return Response(status=200)


@mod.route('/support/ticket/close/<int:id_ticket>', methods=['POST'])
@login_required
def support_delete_ticket_by_id(id_ticket):
    ORM.remove_tickets_by_id(id_ticket)
    return redirect(url_for('support.support'))


@mod.route('/support/<int:user_id>/tickets/all', methods=['GET'])
@login_required
def get_user_tickets_by_id(user_id):
    res = "<ul>"
    list_ticket = ORM.get_user_tickets(user_id)
    for ticket in list_ticket:
        res += f"<li><p>ID ticket: {ticket.id_ticket}</p>" \
            f"<p>Title ticket: {ticket.title_ticket}" \
            f"<p>Is closed?: {ticket.is_closed_ticket}</p></li>"
    res += "</ul>"
    return res


@mod.route('/support/tickets/open/all', methods=['GET'])
@login_required
def get_open_tickets():
    res = "<ul>"
    open_tickets = ORM.get_open_ticket()
    for ticket in open_tickets:
        res += f"<li><p>ID ticket: {ticket.id_ticket}</p>" \
            f"<p>Title ticket: {ticket.title_ticket}" \
            f"<p>Is closed?: {ticket.is_closed_ticket}</p></li>"
    res += "</ul>"
    return res

flask/website/templates/mobile/User/faq.html
{% extends "mobile/base.html" %}

{% block title %}
{{ super() }} | FAQ
{% endblock %}

{% block header %}
        <div class="logo">
            <a href="/home/"><img src="{{ url_for('static', filename='mobile/assets/logo_bikeeper_without_text.png') }}" alt="logo BiKeeper">
            <h1>BiKeeper</h1></a>
        </div>
        {% include "components/mobile-sidebar.html" %}
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='bootstrap/bootstrap.min.css') }}">
        <link rel="stylesheet" href="{{ url_for('static', filename='mobile/css/User/header-mobile.css') }}">
        <link rel="stylesheet" href="{{ url_for('static', filename='mobile/css/User/overlay.css') }}">
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='mobile/css/User/faq.css') }}">
        <nav onclick="openNav()"><img src="{{ url_for('static', filename='mobile/assets/menu.png') }}" alt="logo menu"></nav>
{% endblock %}

{% block main %}


<h2 id="title">FAQ</h2>


{% for category in topic %}

<div class="accordion accordion-flush" id="faq">
  	<div class="accordion-item">
    	<h2 class="accordion-header" id="{{category}}">
      		<button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#i-{{category}}" aria-expanded="false" aria-controls="i-{{category}}">
        		{{category}}
      		</button>
    	</h2>
    	<div id="i-{{category}}" class="accordion-collapse collapse box" aria-labelledby="{{category}}" data-bs-parent="#faq">
    		{% for question in data %}
			{% if data[question]["topic"] == category %}
      		<div class="container-fluid">
				<h4 class="question">{{question}}</h4><br>
				<p class="anwser">{{data[question]["anwser"]}}</p>
				{% if data[question]["optional-link"]!=""  %}
				<a href="{{data[question]['optional-link']}}" class="link">Cliquez ici !</a>
				{% endif %}
			</div>
      		{% endif %}
			{% endfor %}
    	</div>
  	</div>
</div>

{% endfor %}



{% endblock %}

flask/website/templates/mobile/User/guide.html
{% extends "mobile/base.html" %}

{% block title %}
{{ super() }} | FAQ
{% endblock %}

{% block header %}
        <div class="logo">
            <a href="{% if current_user.is_authenticated %}/home/{% else %}{{ url_for('index.index') }}{% endif %}"><img src="{{ url_for('static', filename='mobile/assets/logo_bikeeper_without_text.png') }}" alt="logo BiKeeper">
            <h1>BiKeeper</h1></a>
        </div>
        <link rel="stylesheet" href="{{ url_for('static', filename='mobile/css/User/guide.css') }}">
        {% if current_user.is_authenticated %}
        {% include "components/mobile-sidebar.html" %}
        <link rel="stylesheet" href="{{ url_for('static', filename='mobile/css/User/overlay.css') }}">
        {% else %}
        {% include "components/mobile-sidebar-guest.html" %}
        <link rel="stylesheet" href="{{ url_for('static', filename='mobile/css/Authentification/overlay.css') }}">
        {% endif %}
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='bootstrap/bootstrap.min.css') }}">
        <link rel="stylesheet" href="{{ url_for('static', filename='mobile/css/User/header-mobile.css') }}">
        <nav onclick="openNav()"><img src="{{ url_for('static', filename='mobile/assets/menu.png') }}" alt="logo menu"></nav>
{% endblock %}

{% block main %}
<div class="flash">
    {% include "messages.html" %}
</div>

<section class='landing-banner'>
    <div class="banner"></div>
    <div class="card">
        <div class="card-title">
            <h4>BiKeeper Guide</h4>
        </div>
        
        <p>Welcome in our guide. If you're searching for :</p>
        <ul>
            <li>How to install your device?</li>
            <li>How does your device work?</li>
            <li>How can you get help from BiKeeper?</li>
        </ul>
        <p>Then you're in the right place!</p>
    </div>
</section>

<main>
    <h2>How to install my device?</h2>
    <section class="timeline">

        <div class="container">
            <div class="timeline-item">   
                <div class="timeline-img"></div> 
                <div class="timeline-content timeline-card js--fadeInLeft">
                    <div class="timeline-img-header">
                        <h2>Locate your battery</h2>
                    </div>
                    <div class="date">STEP 1</div>
                    <p>The first step of the installation is to detect the position of your battery. Most of the time, it is located under your tank or your seat.</p>
                </div>
            </div>
    
            <div class="timeline-item">
                <div class="timeline-img"></div>
                <div class="timeline-content timeline-card js--fadeInRight">
                    <div class="timeline-img-header">
                        <h2>Connect the device</h2>
                    </div>
                    <div class="date">STEP 2</div>
                    <p>Once the battery is located, you will have to try to connect the device to the electrical poles of the battery.</p>
                    <p>First, connect the positive terminal which is usually red.</p>
                    <p>Then, do the same with the negative terminal which is often blue or black.</p>
                    <p>The hardest part is done!</p>
                </div>
            </div>
    
            <div class="timeline-item">
                <div class="timeline-img"></div>
                <div class="timeline-content timeline-card js--fadeInLeft">
                    <div class="timeline-img-header">
                        <h2>Remove the adhesive</h2>
                    </div>
                    <div class="date">STEP 3</div>
                    <p>Gently pull the back tab to expose the adhesive portion of the device.</p>
                </div>
            </div>
    
            <div class="timeline-item">
                <div class="timeline-img"></div>
                <div class="timeline-content timeline-card js--fadeInRight">
                    <div class="timeline-img-header">
                        <h2>Affix the Device</h2>
                    </div>
                    <div class="date">STEP 4</div>
                    <p>Fix the device on a flat surface while respecting the direction of the affixing index</p>
                    <p>Your device is now installed! Congratulations!</p>
                </div>
            </div>
    
            <div class="timeline-item">
                <div class="timeline-img"></div>
                <div class="timeline-content timeline-card js--fadeInLeft">
                    <div class="timeline-img-header">
                        <h2>Check for proper installation</h2>
                    </div>
                    <div class="date">STEP 5</div>
                    <p>Now that your device is installed, it is important to check that it is properly connected to your motorcycle. We therefore invite you to turn on the power and test your BiKeeper device right now.</p>
                </div>
            </div>
    
            <div class="timeline-item">
                <div class="timeline-img"></div>
                <div class="timeline-content timeline-card js--fadeInRight">
                    <div class="timeline-img-header">
                        <h2>Good road</h2>
                    </div>
                    <p>the device is now fully ready to live great moments with you! Take care and see you soon!</p>
                    <p>BiKeeper Team</p>
                </div>
            </div>
    
        </div>
    </section>

    <section class='sms'>
        <h2>How does my device work?</h2>
        <p>With BiKeeper you don't have to worry about missing features! We have made a list of all the things that could be useful for you in the future! If you have any questions, please contact us at the following email address: <a href='mailto:bikeeper.team@gmail.com'>bikeeper.team@gmail.com</a></p>

        <h4>First, here are the sms you have to type to use your device :</h4>
        <table>
            <thead>
                <tr><th>SMS</th><th>Description</th></tr>
            </thead>
            <tbody>
                <tr><td>parked</td><td>To activate the park mode on your device. It will switch to anti-theft mode and alert you if necessary.</td></tr>
                <tr><td>unpark</td><td>To deactivate the park mode on your device. The system will no longer theft and vibration.</td></tr>
                <tr><td>start</td><td> The system will start to record your positions and make statistics of your trip. It will also detect vibrations and switch to protection mode.</td></tr>
                <tr><td>stop</td><td>The system will no longer record your journey or protect you. It will also save your journey on your statistics page.</td></tr>
                <tr><td>position</td><td>The system will send you your device position. It is very useful to be sure your motorbike is safe.</td></tr>
            </tbody>
        </table>

        <h4>Also, here's a list of sms you could receive and their signification :</h4>
        <table>
            <thead>
                <tr><th>SMS</th><th>Description</th></tr>
            </thead>
            <tbody>
                <tr><td>Now sync with your device</td><td>Sent when you start your device.</td></tr>
                <tr><td>Your Bike is now unparked</td><td>You deactivated the park mode.</td></tr>
                <tr><td>Your Bike is not parked</td><td>You tried to deactivate park mode while it was already disabled.</td></tr>
                <tr><td>We stopped your journey & your bike is now parked</td><td>Sent when you were on a trip and you activate park mode.</td></tr>
                <tr><td>Your bike is now parked</td><td>You activated the park mode.</td></tr>
                <tr><td>Your Bike is already parked</td><td>You tried to park your motorbike while it was already parked.</td></tr>
                <tr><td>Journey already started please stop it</td><td>A trip is already in progress. Stop it first to start an other one.</td></tr>
                <tr><td>Journey started & your bike is now unparked</td><td>A trip has begun. Your bike is no longer parked.</td></tr>
                <tr><td>Journey started ride safe</td><td>A trip has begun.</td></tr>
                <tr><td>Journey stopped</td><td>A trip just ended.</td></tr>
                <tr><td>Journey not started you can start one</td><td>You tried to stop a journey but there's no trip in progress.</td></tr>
                <tr><td>Vibration detected check your bike</td><td>An important vibration has been detected. You should take a look at your motorbike.</td></tr>
                <tr><td>Bike movement detected check your bike</td><td>Your bike is parked but it is moving!</td></tr>
                <tr><td>Low battery check your bike</td><td>Your battery is low. The device will run on its own battery from now on.</td></tr>
                <tr><td>Fall detected are you fine ?</td><td>Your device has detected an important drop in altitude. Did you fall? Send "Fine" to cancel the alert.</td></tr>
                <tr><td>Ok be safe</td><td>Sent after you answered "Fine" to the sms above.</td></tr>
                <tr><td>Pos<br>lon: ...<br>lat: ...</td><td>Sent when you're asking for the position of your bike by typing "position"</td></tr>
            </tbody>
        </table>
    </section>

    <section class='help'>
        <hr>
        <h2>How can I get help with all of this?</h2>
        <p>BiKeeper Team is dedicated to its community and offers you answers as soon as possible via
        <a href='mailto:bikeeper.team@gmail.com'>bikeeper.team@gmail.com</a>
        <br>or via our <a href="{{ url_for('support.support')}}">online messaging system</a>

        </p>
    </section>

    <div id="thankyou">
        <img src="{{ url_for('static', filename='pc/assets/logo_bikeeper_transparent.png') }}" alt="bikeeper logo">
        <h2>Thank you for choosing BiKeeper!</h2>
    </div>
    
    
</main>

{% endblock %}

flask/website/templates/mobile/User/localisation.html
{% extends "mobile/base.html" %}

{% block title %}
{{ super() }} | Localisation
{% endblock %}

{% block style %}
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='bootstrap/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='mobile/css/User/header-mobile.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='mobile/css/User/overlay.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='mobile/css/User/localisation-mobile.css') }}">
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.3.1/dist/leaflet.css"
            integrity="sha512-Rksm5RenBEKSKFjgI3a41vrjkw4EVPlJ3+OiI65vTjIdo9brlAacEuKOiQ5OFh7cOI1bkDwLqdLw3Zg0cRJAAQ=="
            crossorigin=""/>
    <script type="text/javascript" src="http://code.jquery.com/jquery-1.7.1.min.js"></script>
{% endblock %}


{% block header %}
    {% include "components/mobile-header.html" %}
{% endblock %}

{% block main %}
    <div class="container">
        <div class="row">
            <div class="col-2">
                <a href="{{ url_for('home.home') }}">
                    <i class="fa fa-chevron-left"></i>
                </a>
            </div>
            <div class="col-8">Localisation</div>
        </div>
    </div>
    <div class="container-fluid">
        
    </div>
    <div id="map">
        <!-- Ici s'affichera la carte -->
    </div>
{% endblock %}


{% block script %}
<script>
    {% autoescape false %}
    const username_home = '{{ current_user.username_user }}';
    const selected_device = '{{ current_user.selected_device }}';
    {% endautoescape %}
</script>
<script src="https://unpkg.com/leaflet@1.3.1/dist/leaflet.js"
        integrity="sha512-/Nsx9X4HebavoBvEBuyp3I7od5tA0UzAxs+j83KgC8PU0kgB4XiK4Lfe4y4cgBtaRJQEIFCW+oC506aPT2L1zw=="
        crossorigin=""></script>
<script src="{{ url_for('static', filename='pc/js/home_map.js') }}"></script>
{% endblock %}

flask/website/templates/mobile/User/support-bis.html
{% extends "mobile/base.html" %}

{% block title %}
{{ super() }} | Support
{% endblock %}

{% block header %}
    <div class="logo">
        <a href="/home/"><img src="{{ url_for('static', filename='mobile/assets/logo_bikeeper_without_text.png') }}" alt="logo BiKeeper">
        <h1>BiKeeper</h1></a>
    </div>
    {% include "components/mobile-sidebar.html" %}
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='bootstrap/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='mobile/css/User/header-mobile.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='mobile/css/User/overlay.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='mobile/css/User/support-mobile.css') }}">
    <!-- Use any element to open/show the overlay navigation menu -->
    <nav onclick="openNav()"><img src="{{ url_for('static', filename='mobile/assets/menu.png') }}" alt="logo menu"></nav>
{% endblock %}

{% block main %}
    <div class="container">
        <div class="row">
            <div class="col-2"><a href="/support/"><i class="fa fa-chevron-left"></i></a></div>
            <div class="col-8">TICKET #{{ id_ticket }}</div>
            {% if current_user.is_admin_user %}
                <div class="col-1 check">
                    <form id="deleteTicketForm" action="{{ url_for('support.support_delete_ticket') }}/{{ id_ticket }}" method="POST">
                        <button type="submit" id="btn-close">
                            <i class="fa fa-check"></i>
                        </button>
                    </form>
                </div>
            {% endif %}
        </div>
    </div>
    <section class='chat'>
        <div class="container" id="chat-{{ id_ticket }}"></div>

    </section>
    <div class="blank"></div>

    <div class="container-fluid" id="input-message">
        <div class="row">
            <div class="col-8"><input type="text" value="Write your message" name="msg" id="msg"></div>
            <div class="col-2"><button type="button"><i class="fa fa-paperclip"></i></button></div>
            <div class="col-2"><button type="submit" class="submit" id="send-msg"><i class="fa fa-paper-plane"></i></button></div>
        </div>
    </div>
{% endblock %}


{% block script %}
<script type="text/javascript">
    {% autoescape false %}
    var current_user = '{{current_user.username_user}}';
    var is_admin = '{{current_user.is_admin_user}}';
    var user_image = '{{picture}}';
    {% endautoescape %}

    function isAdmin(){
        return is_admin;
    }

    function getUsername() {
        return current_user;
    }

    function getImageUser(){
        return user_image;
    }
    function checkRadioButton(elem) {
        elem.nextSibling.nextSibling.checked=true
    }

</script>
<script type="text/javascript" src="{{ url_for('static', filename='utils.js') }}" defer></script>
<script type="text/javascript" src="{{ url_for('static', filename='mobile/js/support.js') }}" defer></script>
{% endblock script %}

flask/website/templates/mobile/User/support.html
{% extends "mobile/base.html" %}

{% block title %}
{{ super() }} | Support
{% endblock %}

{% block style %}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='bootstrap/bootstrap.min.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='mobile/css/User/header-mobile.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='mobile/css/User/overlay.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='mobile/css/User/support-mobile.css') }}">
{% endblock %}

{% block header %}
  {% include "components/mobile-header.html" %}
{% endblock %}

    
{% block main %}
<section class='tickets'>
    {% if not current_user.is_admin_user %}
    <a href="{{ url_for('home.home') }}" class="goback">
    {% else %}
    <a href="{{ url_for('admin.admin_home') }}" class="goback">
    {% endif %}
      <i class="fa fa-chevron-left"></i>
    </a>
    <div>
        <div class="container">
            <div class="container-fluid">
                <h3>TICKETS</h3>
            </div>
        </div>
        <div class="container">
            <ul class="nav">
            {% for numero in messages.keys() %}
            <div class="container-fluid tckt">
                <li onclick="" >
                    <a href="/support/{{ numero }}/" class="tckt-id">
                        Ticket#{{ numero }}
                    </a>
                    <p class="lst-msg">{{ last_messages[numero]["content"]  }}</p>
                </li>
            </div>
                
            {% endfor %}
        </ul>
        </div>
        

        

        {% if not current_user.is_admin_user %}
        <button type="button" class="btn btn-primary why-btn" data-bs-toggle="modal" data-bs-target="#exampleModal">
          Nous contacter
        </button>
        {% endif %}



        <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Pourquoi nous contactez-vous ?</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>
              <form action="{{ url_for('support.support_new_ticket') }}" method='POST'>
                  <div class="modal-body">
                    <fieldset>
                        <input type="text" name="ticket" placeholder='I need you because...'>
                    </fieldset>
                  </div>
                  <div class="modal-footer">
                    <button type="submit" class="btn btn-secondary" data-bs-dismiss="modal">Valider</button>
                  </div>
              </form>
            </div>
          </div>
        </div>
    </div>
</section>

{% endblock main %}






{% block script %}
<script type="text/javascript">
        {% autoescape false %}
        var current_user = '{{current_user.username_user}}';
        var is_admin = '{{current_user.is_admin_user}}';
        var user_image = '{{picture}}';
        {% endautoescape %}

        function isAdmin(){
            return is_admin;
        }

        function getUsername() {
            return current_user;
        }

        function getImageUser(){
            return user_image;
        }

</script>
<script src="{{ url_for('static', filename='pc/js/support.js') }}" defer></script>
{% endblock script %}